### ISSUE TITLE
Build fails with skalibs 2.6.4

### ISSUE THREAD

**Issue by timburgess** [jprjr/sockexec#10]
I'm trying to build with skalibs 2.6.4 and it fails with:

```
ubuntu@server-4:~/src/sockexec-2.0.3_ make
gcc -static -Wall -Werror -c -o src/accept_client.o src/accept_client.c
In file included from src/accept_client.c:1:0:
src/common.h:25:21: error: conflicting types for _environ_
 extern const char **environ;
                     ^
In file included from /usr/include/skalibs/webipc.h:16:0,
                 from src/common.h:9,
                 from src/accept_client.c:1:
/usr/include/skalibs/posixplz.h:14:15: note: previous declaration of _environ_ was here
 extern char **environ ;
               ^
Makefile:56: recipe for target 'src/accept_client.o' failed
make: *** [src/accept_client.o] Error 1
```

OS is Ubuntu 16.04.1 LTS
